POST http://localhost:8080/products HTTP/1.1
content-type: application/json

{
    "name":"Harina de trigo x 3Kg",
    "brand": {
        "name": "Haz de oros"
    },
    "category": {
        "name": "Harinas",
        "parent": "Mercado"
    }
}